# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-23 18:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_auto_20170121_0938'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idp', models.IntegerField()),
                ('title', models.CharField(max_length=500)),
                ('pic', models.FileField(upload_to=b'')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
