# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-23 19:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_transport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transport',
            name='pic',
        ),
    ]
