# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-23 19:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_remove_transport_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='transport',
            name='logo',
            field=models.FileField(default='https://yt3.ggpht.com/-bFtBlD-ddNY/AAAAAAAAAAI/AAAAAAAAAAA/VNFfgN6JdmQ/s100-c-k-no-mo-rj-c0xffffff/photo.jpg', upload_to=b''),
        ),
    ]
